name: Bug Report
description: Reportar um bug ou comportamento inesperado
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Preencha as informações abaixo para nos ajudar a resolver.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Uma descrição clara do que está acontecendo
      placeholder: Descreva o bug aqui...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Como podemos reproduzir o bug?
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que você esperava que acontecesse?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que realmente aconteceu?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Se tiver, cole logs de erro ou screenshots aqui
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Sistema Operacional
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Versão do Python
      placeholder: "ex: 3.12"
